replicaCount: 1

serviceAccount:
  create: false

autoscaling:
  enabled: false

image:
  repository: deno-container
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

deno:
  SERVER_PORT: "8000"
  DB_HOST: "127.0.0.1"
  DB_PORT: "3306"

mysql:
  MYSQL_DATABASE: employees
  MYSQL_USER: user
  args: 
    - "--default-authentication-plugin=mysql_native_password"

ingress:
  enabled: false
