version: '3'

services:
  web:
    build: .
    container_name: deno-container
    environment:
      - DB_HOST=deno-mysql
      - DB_PORT=3306
      - DB_PASSWORD=my-secret-pw
      - SERVER_PORT=8000
    ports:
      - "8000:8000"
  mysql:
    image: mysql:8.0
    container_name: deno-mysql
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=employees
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./sqls:/docker-entrypoint-initdb.d:ro
