apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-sql
data:
  tables.sql: |-
    USE employees;
    -- Adjacency List Model
    CREATE TABLE employees (
        id INT PRIMARY KEY,
        name VARCHAR(100),
        supervisor_id INT,
        FOREIGN KEY (supervisor_id) REFERENCES employees(id)
    );
