apiVersion: v1
kind: Secret
metadata:
  name: deno-secret
type: Opaque
data:
  DB_PASSWORD: {{ "my-secret-pw" | b64enc }}
  scrypt_basic_auth_users: {{ "'[[\"chris\",\"c2NyeXB0AAwAAAAIAAAAATpP+fdQAryDiRmCmcoOrZa2mZ049KdbA/ofTTrATQQ+m0L/gR811d0WQyip6p2skXVEMz2+8U+xGryFu2p0yzfCxYLUrAaIzaZELkN2M6k0\"]]'" | b64enc }}
  DB_ROOT_PASSWORD: {{ "my-secret-pw" | b64enc }}
